#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-File-ShareDir
Version  : 1.106
Release  : 3
URL      : http://search.cpan.org/CPAN/authors/id/R/RE/REHSACK/File-ShareDir-1.106.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/R/RE/REHSACK/File-ShareDir-1.106.tar.gz
Summary  : 'Locate per-dist and per-module shared files'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-File-ShareDir-doc
BuildRequires : perl(Class::Inspector)

%description
# NAME
File::ShareDir - Locate per-dist and per-module shared files
# SYNOPSIS
use File::ShareDir ':ALL';

# Where are distribution-level shared data files kept
$dir = dist_dir('File-ShareDir');

# Where are module-level shared data files kept
$dir = module_dir('File::ShareDir');

# Find a specific file in our dist/module shared dir
$file = dist_file(  'File-ShareDir',  'file/name.txt');
$file = module_file('File::ShareDir', 'file/name.txt');

# Like module_file, but search up the inheritance tree
$file = class_file( 'Foo::Bar', 'file/name.txt' );

%package doc
Summary: doc components for the perl-File-ShareDir package.
Group: Documentation

%description doc
doc components for the perl-File-ShareDir package.


%prep
%setup -q -n File-ShareDir-1.106

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/File/ShareDir.pm
/usr/lib/perl5/site_perl/5.26.1/auto/share/dist/File-ShareDir/sample.txt
/usr/lib/perl5/site_perl/5.26.1/auto/share/dist/File-ShareDir/subdir/sample.txt
/usr/lib/perl5/site_perl/5.26.1/auto/share/module/File-ShareDir/test_file.txt

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/man/man3/*
